### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by dadiwonton** [JoePenna/Dreambooth-Stable-Diffusion#14]
Hi, I'm absolutely new here and coming in from Corridor Crew and AItrepreneur and can't seem to get past the training step. This is the error that I seem to face now. Thanks in advance and good luck with the project 💯 

`Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Traceback (most recent call last):
  File "main.py", line 651, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 41, in load_model_from_config
    model.cuda()
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 138, in cuda
    return super().cuda(device=device)
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 868, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined`

**Comment by dadiwonton** [comment]
My first error was that my training got killed immediately after it starts training. So I tried for some time to train again until this error popped up.

**Comment by jooshkins** [comment]
Having similar issues
This might just be a coincidence, but I got the `RuntimeError: No CUDA GPUs are available` error, when running on a RTX 3090
Switched to a RTX A5000 and that error went away. 
But I am now having the issue where like [dadiwonton](https://github.com/dadiwonton) described where it is killed right after starting to train:
```
Epoch 0:   0%|                                         | 0/2020 [00:00<?, ?it/s]/venv/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:72: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:229: UserWarning: You called `self.log('global_step', ...)` in your `training_step` but the value needs to be floating point. Converting it to torch.float32.
  warning_cache.warn(
Epoch 0:   0%| | 1/2020 [00:02<1:40:08,  2.98s/it, loss=0.0382, v_num=0, train/lHere comes the checkpoint...
Killed
```

**Comment by Invixvb** [comment]
> Having similar issues This might just be a coincidence, but I got the `RuntimeError: No CUDA GPUs are available` error, when running on a RTX 3090 Switched to a RTX A5000 and that error went away. But I am now having the issue where like [dadiwonton](https://github.com/dadiwonton) described where it is killed right after starting to train:
> 
> ```
> Epoch 0:   0%|                                         | 0/2020 [00:00<?, ?it/s]/venv/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:72: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
>   warning_cache.warn(
> /venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:229: UserWarning: You called `self.log('global_step', ...)` in your `training_step` but the value needs to be floating point. Converting it to torch.float32.
>   warning_cache.warn(
> Epoch 0:   0%| | 1/2020 [00:02<1:40:08,  2.98s/it, loss=0.0382, v_num=0, train/lHere comes the checkpoint...
> Killed
> ```

Saw a YT Comment about your issue:
> If you get the error about it being killed after 1 step, open the terminal, type "ps aux" and look for the pid for both python relauncher and webui, then type "kill (the id for either)" and kill both of them.  Was stuck on that error for a while with an A5000 but this fixed my problem.

I'm having the same issue on an A5000 as @dadiwonton where it doesn't even start an iteration. Same error

**Comment by jooshkins** [comment]
Ahh thanks mate! Killing those processes seemed to clear it up, and it is training now. 
Will see it finishes 🤞

**Comment by djbielejeski** [comment]
Lots of good help on [discord](https://discord.com/invite/qbMuXBXyHA).
