### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 114.00 MiB

### ISSUE THREAD

**Issue by Larcebeau** [JoePenna/Dreambooth-Stable-Diffusion#39]
Hello, thank u in advance. I'v this issue and i don't know result it...

Training complete. max_training_steps reached or we blew up.
Traceback (most recent call last):
  File "main.py", line 848, in <module>
    trainer.fit(model, data)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 266, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1646, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/venv/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/torch/optim/adamw.py", line 129, in step
    state['exp_avg_sq'] = torch.zeros_like(p, memory_format=torch.preserve_format)
RuntimeError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 15.74 GiB total capacity; 10.43 GiB already allocated; 49.69 MiB free; 10.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by swcrazyfan** [comment]
I've been having the same issue. I've followed the steps multiple times trying both 3090 and A5000 on the regular and community areas, but nothing works.

**Comment by Larcebeau** [comment]
I don't know why

**Comment by Larcebeau** [comment]
I've something for you. In my case it was because one of my photo aren't in 512 x 512 after checking. In resize it and it's done. But now... my training is killed so... Solve an issue and you've an other one ahah

**Comment by rrweller** [comment]
I checked my dataset and I had one image that was 511x512. I fixed it but I still get this error

**Comment by Larcebeau** [comment]
Hum, i restart a pod on Runpod because i think i do not allowed 60 GB Disk and 60 Gb Volume. When u changed Pytorch to Stable Diff, its reset. I retry it, make the changes and it was okay for me

**Comment by Larcebeau** [comment]
But my training was killed after. It is happen to you, you have a the correction on issues section. Sorry for my ENglish

**Comment by rrweller** [comment]
> When u changed Pytorch to Stable Diff, its reset.

Not sure I understand. Using a different version of pytorch made your CUDA memory error go away?

**Comment by Larcebeau** [comment]
Not for me. i stayed on Stable diffusion, 
I assure myself that i had wrote 60 GB disk and 60 GB Volume and after i run. After, before opening the Joepenna Run pod. You need to open Terminal and kills two cells. 
In Terminal open a new tab, and type "ps aux" to find the PID for relauncher and webui, kill both process and restart the training. Otherwise your trainig will be killed. And after, train normally.

**Comment by Larcebeau** [comment]
Oh Sorry, you don't understand. So before you lunch note pad u need to check if your GB disk and GB volume are enough. Per default it is 20/20. You need to have 60/60 on RunPod.

**Comment by nikolak** [comment]
Is the pod memory usage at 0% on the runpod website under my pods? For me, it wasn't. It was at a few % usage. Restarting the pod fixed the issue.

**Comment by swcrazyfan** [comment]
Restart the notebook. Then, try to run things.

**Comment by 0xdevalias** [comment]
> You need to open Terminal and kills two cells.
> In Terminal open a new tab, and type "ps aux" to find the PID for relauncher and webui, kill both process and restart the training. Otherwise your trainig will be killed. And after, train normally.

^this

See also:

- https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/95

>  For those on runpod either do what's suggested above or connect to a web terminal and kill those two processes:
>
> ```
> sh -c python webui.py --port 3000 --ckpt /workspace/stable-diffusion-webui/v1-5-pruned-emaonl...
> python webui.py --port 3000 --ckpt /workspace/stable-diffusion-webui/v1-5-pruned-emaonly.ckpt...
> ```
> 
> _Originally posted by @zoellner in https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/95#issuecomment-1297853208_
